# Generated by Django 5.0.4 on 2024-07-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixmonths2024', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semiannual2024report',
            name='field_25_100',
            field=models.PositiveIntegerField(default=0, verbose_name='Уволено по иным причинам'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во оконченых расследованием уд с направлением в суд за период с 01.01 по 30.06.2024 из сопровождаемых (с остатком прошлых лет)'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_13',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во приговоров вступивших в законную силу за период с 01.01 по 30.06.2024 по сопровождаемым уголовным делам (с остатком прошлых лет)'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Фактическая численность СБ (чел.) на 30.06.2024'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_20',
            field=models.PositiveIntegerField(default=0, verbose_name='Выявлено фактов с 01.01. по 30.06.2024'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_25',
            field=models.PositiveIntegerField(default=0, verbose_name='Уволено по результатам служебных проверок'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_26',
            field=models.PositiveIntegerField(default=0, verbose_name='Проведено проверок несения службы за период с 01.01. по 30.06.2024'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_3',
            field=models.PositiveIntegerField(default=0, verbose_name='Направлено заявлений в правоохранительные органы за период с 01.01 по 30.06.2024 (кол-во без дебиторской задолженности)'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_30',
            field=models.PositiveIntegerField(default=0, verbose_name='По выявленным нарушениям направлено претензионных писем за период с 01.01 по 30.06.2024'),
        ),
        migrations.AlterField(
            model_name='semiannual2024report',
            name='field_34',
            field=models.PositiveIntegerField(default=0, verbose_name='В период с 01.01 по 30.06.2024 изучено юр. лиц (подрядчики , субподрядчики), принявшие участие в закупочных процедурах (кол-во)'),
        ),
    ]
