# Generated by Django 5.0.3 on 2024-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(verbose_name='Отчётная дата'),
        ),
    ]
