# Generated by Django 5.0.3 on 2024-03-21 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_dailyreport_report_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorsSummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creators', models.ManyToManyField(related_name='summary_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
