# Generated by Django 5.0.3 on 2024-03-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_dailyreport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='field_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Незакрытие постов охраны'),
        ),
    ]
