# Generated by Django 5.0.4 on 2024-04-14 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondata', '0001_initial'),
        ('daily', '0006_alter_dailyreport_field_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commondata.department', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='department',
            field=models.ManyToManyField(to='commondata.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
