# Generated by Django 5.0.6 on 2024-07-16 04:01

import django.core.validators
import django.db.models.deletion
import investigations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('order_date', models.DateField(verbose_name='Дата приказа')),
                ('order_num', models.CharField(max_length=100, verbose_name='Номер приказа')),
                ('brief_summary', models.TextField(verbose_name='Краткая фабула проверки')),
                ('initiator', models.CharField(max_length=200, verbose_name='Инициатор проверки')),
                ('end_date', models.DateField(verbose_name='Дата окончания проверки')),
                ('extended_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания при продлении')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершена'), ('suspended', 'Приостановлена')], default='in_progress', max_length=20, verbose_name='Текущее состояние по проверке')),
                ('damage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ущерб (млн. руб.)')),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возмещено/предотвращено (млн. руб)')),
                ('outcome_summary', models.TextField(verbose_name='Краткое описание итогов')),
                ('num_employees_discipline', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество работников, привлечённых к дисциплинарной ответственности (в т.ч. депремировано)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.department', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=investigations.models.invests_directory_path)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='investigations.investigation')),
            ],
        ),
    ]
