# Generated by Django 5.0.4 on 2024-07-29 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_investigantioncreatorssummaryreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestigantionCreatorsSummaryReport',
            new_name='InvestigationCreatorsSummaryReport',
        ),
    ]
