# Generated by Django 5.0.4 on 2024-08-05 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_rename_investigantioncreatorssummaryreport_investigationcreatorssummaryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='num_employees_discipline',
        ),
        migrations.AddField(
            model_name='investigation',
            name='inspection_type',
            field=models.CharField(choices=[('poor_contract_performance', 'Некачественное исполнение договорных обязательств'), ('procurement_violations', 'Нарушение закупочных процедур'), ('unaccounted_materials', 'Хранение неучтенных ТМЦ'), ('personnel_violations', 'Нарушения в работе персонала'), ('other', 'Иное')], default='other', max_length=50, verbose_name='Тип служебной проверки'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='num_employees_discipline_demotion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество работников, привлечённых к дисциплинарной ответственности (депремировано)'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='num_employees_discipline_fired',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество работников, привлечённых к дисциплинарной ответственности (уволено)'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='num_employees_discipline_reduction',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество работников, привлечённых к дисциплинарной ответственности (понижено в должности)'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='num_employees_discipline_reprimand',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество работников, привлечённых к дисциплинарной ответственности (выговор)'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='num_employees_discipline_warning',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество работников, привлечённых к дисциплинарной ответственности (замечание)'),
        ),
    ]
