# Generated by Django 5.0.7 on 2024-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_remove_investigation_num_employees_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='brief_summary',
            field=models.TextField(blank=True, max_length=400, verbose_name='Краткая фабула проверки'),
        ),
    ]
