# Generated by Django 5.0.7 on 2024-08-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0006_alter_investigation_num_employees_discipline_demotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='brief_summary',
            field=models.TextField(blank=True, max_length=800, verbose_name='Краткая фабула проверки'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='order_num',
            field=models.CharField(max_length=50, verbose_name='Номер приказа'),
        ),
    ]
