# Generated by Django 5.0.4 on 2024-04-17 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commondata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('report_date', models.DateField(verbose_name='Отчётная дата')),
                ('field1', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Экономический эффект (сумма, в млн. руб. без НДС)')),
                ('field2', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field3', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Выявлено неучтённых ТМЦ (сумма, в млн. руб. без НДС)')),
                ('field4', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field5', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Входной контроль (сумма, в млн. руб. без НДС)')),
                ('field6', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field7', models.PositiveIntegerField(default=0, verbose_name='Количество запросов, актов реагирования от\nконтрольно-надзорых и правоохранительных органов,\nпоступивших в отчётном периоде')),
                ('field8', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field9', models.PositiveIntegerField(default=0, verbose_name='Количество запросов, актов реагирования, поручений\nиз территориальных органов власти, поступивших\nв отчётном периоде')),
                ('field10', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field11', models.PositiveIntegerField(default=0, verbose_name='Направлено заявлений в правоохранительные органы\nдля защиты интересова Компании')),
                ('field12', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field13', models.PositiveIntegerField(default=0, verbose_name='Проведено встреч, рабочих групп с сотрудниками\nправоохратиельных органов, контрольно-нажзорных органов')),
                ('field14', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field15', models.PositiveIntegerField(default=0, verbose_name='Выявлено фактов антикорпоративных проявлений')),
                ('field16', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field17', models.PositiveIntegerField(default=0, verbose_name='Инициировано служеюных проверок')),
                ('field18', models.CharField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример')),
                ('field19', models.CharField(blank=True, max_length=2000, verbose_name='Значимая информация, факты, события, риски и т.д.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commondata.department')),
            ],
        ),
    ]
