# Generated by Django 5.0.4 on 2024-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='field10',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field12',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field14',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field16',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field18',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field19',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Значимая информация, факты, события, риски и т.д.'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field2',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field4',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field6',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field8',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Наиболее значимый пример'),
        ),
    ]
