# Generated by Django 5.0.4 on 2024-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_weekly', '0002_alter_weeklyreport_field10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='field17',
            field=models.PositiveIntegerField(default=0, verbose_name='Инициировано служебных проверок'),
        ),
    ]
