# Generated by Django 5.0.4 on 2024-04-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commondata', '0001_initial'),
        ('general_weekly', '0005_weeklycreatorssummaryreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commondata.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Экономический эффект (сумма, в млн. руб. без НДС)'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field10',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field12',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field13',
            field=models.PositiveIntegerField(default=0, verbose_name='Проведено встреч, рабочих групп с сотрудниками\nправоохратиельных органов, контрольно-надзорных органов'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field14',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field16',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field18',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field2',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field4',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field6',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field8',
            field=models.TextField(blank=True, max_length=1800, verbose_name='Наиболее значимый пример'),
        ),
    ]
