# Generated by Django 5.0.4 on 2024-04-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_weekly', '0007_alter_weeklyreport_field5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='field3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Выявлено неучтённых ТМЦ (сумма, в млн. руб. без НДС)'),
        ),
    ]
