# Generated by Django 5.0.4 on 2024-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_weekly', '0008_alter_weeklyreport_field3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='field1',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='Экономический эффект (сумма, в млн. руб. без НДС)'),
        ),
    ]
