# Generated by Django 5.0.4 on 2024-04-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_weekly', '0009_alter_weeklyreport_field1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='field3',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='Выявлено неучтённых ТМЦ (сумма, в млн. руб. без НДС)'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='field5',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='Входной контроль (сумма, в млн. руб. без НДС)'),
        ),
    ]
